examples/geometry/src/geometry/components.cljs
examples/geometry/src/geometry/core.cljs

I wrote this to add a history slider to the geometry example app for a presentation I gave recently ([this one](https://github.com/bmaddy/presentations/tree/master/2015-minnebar/)). I figured I'd push it back just in case you guys wanted it in your demo. Thanks for all your hard work on Reagent!

adds a history slider to the geometry example app

---

README.md

There was a link in the README.md that indicated the reagent repo had moved, but the link pointed back to this exact project. Removed it.

Remove recursive link in the readme

---

src/reagent/ratom.cljs

Quoting [Clojurescript 0.0-2755 release notes](https://groups.google.com/forum/#!topic/clojurescript/FoiqNV5nunQ):
> The first [improvement] is around macros. If your library does the following:
(ns foo.bar
(:require-macros foo.bar))
> Then users that require your library:
(ns bar.baz
(:require [foo.bar :as foo]))
> Will get  `foo.bar` macros automatically required and aliased to `foo`.
I think it would be a useful convention to require macros of respective Clojure namespaces. Is there a reason I might be not aware of that this hasn't been done? I'm new to Reagent :-)

require reagent.ratom macros in cljs namespace

---

README.md

After extensive discussion in https://github.com/reagent-project/reagent/issues/161 it appears a number of new people get confused by the use of the referred reagent atom (because it's named the same as clojure.core/atom). Changing this page (and other parts of the documentation) to use an aliased namespace directly without using a referred version of atom *may* decrease the number of confused people. This is largely an experiment to see if it helps. (It can't hurt!) :)

Make references to atom explicit, not referred

---

src/reagent/impl/template.cljs

Correctly repositions the cursor - fixes #79

Position cursor after an input's value has changed

---

README.md

For better compatiblity with figwheel, change the two references that are def'd with r/atom values to be defonce so they persist through code updates.

Change r/atom defs to defonce in readme

---

src/reagent/ratom.cljs
test/reagenttest/testratom.cljs

We hit upon a problem where some of our auto-run reactions would not re-run, despite the things they deref'd changing value. To demonstrate: the new test in this PR will fail in current master, but pass with the patch applied. All other tests still pass with the patch applied.
Having >= 2 deref'd reactions that rely on the modified state is key to reproducing. Here's my best go at an english explanation for what's happening:
- `swap!` at test's line 254 happens
- atom notifies its watches (c1 & c2)
- `c1` runs, has changed, & notifies its watches (`rxn`)
- `(capture-derefed <rxn's body>)` runs
- _(... rxn's body runs ...)_
- we `swap!` at the very end of rxn's body
- the atom notifies its watches (c1 and c2)
- `c1` runs, but hasn't changed, so it doesn't notify `rxn`
- `c2` runs, has …

Fix bug where some auto-run reactions don't re-run

---

project.clj

The latest Cljsjs React build adds missing nativeEvent property for
SyntheticEvent object on the extern file.
https://github.com/cljsjs/packages/commit/0db9cd856e6d5e35f275811225143233bc43048b

Update Cljsjs React dependency

---

README.md

Just a tiny conflict between importing as `r` but using as `reagent` in the first example.

Fixes require typo in readme example

---

src/reagent/ratom.cljs
test/reagenttest/testcursor.cljs
test/reagenttest/testwrap.cljs

I'm not sure what the motivation behind #128 was, as the & syntax doesn't work with deftype and the core swap! function does this destructuring already. I added some tests for the old ISwap implementations, and they seem to work as expected.

Revert #128 and add tests for ISwap implementations

---

demo/reagentdemo/syntax.clj
src/reagent/interop.clj

This PR contains 2 changes that makes reagent self-host compatible:
1. remove JVM related code in macro files
2. remove [deprecated macro code](https://github.com/reagent-project/reagent/blob/master/src/reagent/interop.clj#L59-L75) as it causes trouble in self-host cljs. See the problematice code in [klipse](http://app.klipse.tech/?cljs_in=%0A(defmacro%20.%27%20%5B%26%20args%5D%0A%20%20%3B%3B%20Deprecated%20since%20names%20starting%20with%20.%20cause%20problems%20with%20bootstrapped%20cljs.%0A%20%20(let%20%5Bns%20(str%20cljs.analyzer%2F*cljs-ns*)%0A%20%20%20%20%20%20%20%20line%20(%3Aline%20(meta%20%26form))%5D%0A%20%20%20%20(binding%20%5B*out*%20*err*%5D%0A%20%20%20%20%20%20(println%20%22WARNING%3A%20reagent.interop%2F.%27%20is%20deprecated%20in%20%22%20ns%20%22%20line%20%22%20line%0A%20%2 …

Make reagent self-host compatible

---

CHANGELOG.md
src/reagent/core.cljs
src/reagent/debug.clj
src/reagent/impl/batching.cljs
src/reagent/impl/component.cljs
src/reagent/impl/util.cljs
src/reagent/interop.clj
src/reagent/ratom.clj
src/reagent/ratom.cljs

This aims to steer away from error messages like this:

Improve assert messages all around

---

project.clj
src/reagent/core.cljs
src/reagent/impl/util.cljs
src/reagent/ratom.cljs
test/reagenttest/testreagent.cljs

Old implementation incorrectly used variadic arity for -invoke
implementation. Variadic artities for protocols are not supported by
Cljs. The old code as worked by luck but was broken by a recent change:
https://dev.clojure.org/jira/browse/CLJS-2099
New implementation properly implements all the artities for -invoke. New
implementation creates the partial fn in a constructor function, so -invoke
code doesn't need to do that. New implementation also implements Fn.

Fix partial-ifn with latest Cljs

---

README.md
src/reagent/impl/template.cljs
test/reagenttest/testreagent.cljs

That's my first stab at adding support for passing a collection for class property, as mentioned in #138. Is that the right place to implement it?

Added support for collections in :class property

---

src/reagent/core.cljs
src/reagent/impl/template.cljs

Submitting PR for review and discussion at this stage.
**Problem:** Reagent controls text input components to handle updates and caret repositioning correctly, but this assumes that only `<input>` elements are rendered by text input components in Hiccup. This excludes Reagent users that, for example, wrap their `<input>` element in a `<div>` or otherwise have arbitrary behaviour/structure. The result is that these components have caret positioning bugs, as seen in #265.
**Proposed solution:** Add more affordances to Reagent's input handling API so that "synthetic" input components (i.e. not just rendering `<input>` at the root) can inform Reagent of how to locate the correct input element to manage within its DOM tree; and what to do when values change.
In particular, in `template.cljs`: …

Support synthetic text input components

---

src/reagent/ratom.cljs
test/reagenttest/testratom.cljs

Add IWithMeta protocol to RAtom

---

src/reagent/impl/template.cljs
test/reagenttest/testreagent.cljs

Custom element names must always contain hyphen so we can use that to
keep track of which elements are native vs. custom when parsing tag
name.
Fixes #322
I don't like much copying twenty lines of code (prop renaming), but seemed like the easiest, and probably most efficient way to do this. Parse-tag result is cached, so per different hiccup-tag, we need to check if name contains hyphens only once. Then convert-props can use this `custom` property from parsed object to select which function to use to convert props to JS.
I moved the handling for ID and class from hiccup-tag so it modifies the Clojure props map, instead of JS object. This could have some effect on performance.

Don't rename props for custom elements

---

README.md

Not sure if this belong in the readme yet because they're some draft being linked to, but I found these documentations more useful than the API Documentation. I think it's worth pointing to.

Add link to FAQ and tutorials

---

src/reagent/impl/component.cljs

Under [certain conditions](https://dev.clojure.org/jira/browse/CLJ-2325), `not=` in the default `shouldComponentUpdate` function can throw an exception.
You can boil this down to:
```cljs
cljs.user=> (not= {:todos 1} (sorted-map 1 2))
Cannot compare :todos to 1
cljs.core/-compare [cljs.core/IComparable] (cljs/core.cljs:9995:14)
-compare (cljs/core.cljs:807:24)
compare (cljs/core.cljs:2360:5)
entry-at (cljs/core.cljs:8401:25)
cljs.core/-lookup [cljs.core/ILookup] (cljs/core.cljs:8468:24)
cljs.core/-equiv [cljs.core/IEquiv] (cljs/core.cljs:6560:32)
-equiv (cljs/core.cljs:695:23)
= (cljs/core.cljs:1247:16)
```
This is ultimately a bug in ClojureScript (and Clojure), but in the general case, `not=` doesn't guarantee that it won't throw, and there are weird edge cases like this that pop up now …

Catch not= throwing exceptions and log a warning

---

doc/UsingHiccupToDescribeHTML.md

I added docs for the special notation of ids and classes (`#id` and `.class`). 
More or less stolen from here: 
https://www.reddit.com/r/Clojure/comments/75d054/hiccupreagent_syntax_help/do5o0qh/

Docs: Add special notation for id and classes

---

doc/CreatingReagentComponents.md

This commit adds a brief description and examples of the usage of React Fragments via the `:<>` Hiccup form.

Updated to include a description of Fragments.

---

doc/InteropWithReact.md

https://reactjs.org/docs/higher-order-components.html#dont-use-hocs-inside-the-render-method

Fix InteropWithReact.md for "Don’t Use HOCs Inside the render Method"

---

doc/WhenDoComponentsUpdate.md

Keep the order of usage the same as the order declared, so child #1 is used first & child #2 is used second.

small rearrangement

---

src/reagent/core.cljs
src/reagent/impl/util.cljs
test/reagent/impl/util_test.cljs
test/reagenttest/runtests.cljs

We've run into a few instances of people trying to use `reagent.core/merge-props` like `clojure.core/merge`, with multiple maps.  For an example, think of something like this:
```clojure
(r/merge-props
{:style {:display "flex" :flex-direction "flex-column"}}
(when @loading
{:disabled true {:style {:background-color "gray"}}})
(when @demo
{:class "demo-list"}))
```
This doesn't change the behavior of `merge-props` for existing code.  (Unless people were relying on having `(merge-props {})` throw an error?)

Allows for an arbitrary number of props in merge-props

---

src/reagent/impl/util.cljs

Fixes #385 
I forked from 0.7.0 ~~since I selfishly would like to see this in a 0.7.1 (if its not a pain).
But if not~~ it should cleanly merge on HEAD/0.8x.
Thanks!

Comparing PartialFn to nil is false/unexceptional #385

---

doc/UsingSquareBracketsInsteadOfParens.md

The link to When do components update was broken in the docs. This fixes it. I have tested this change locally by running lein codox and checking the link that it generates.

Fix link to next tutorial

---

examples/material-ui/project.clj

Material-ui 4.1.0-0 requires react/react-dom 16.8.3

Fix material-ui example for version 4.1.0-0

---

demo/reagentdemo/intro.cljs

Most importantly, the keys link stopped resolving to anything useful.

Update react documentation links in intro.cljs

---

src/deps.cljs

This adds transitive dependency resolution for [shadow-cljs](http://shadow-cljs.org/).
shadow-cljs does not support CLJSJS `:foreign-libs`, instead favouring direct NPM dependencies. The official way for libraries to support providing transitive NPM dependencies to shadow-cljs is a `:npm-deps` key in a `deps.cljs` file as per this PR.
shadow-cljs will read all found `deps.cljs` with `:npm-deps` on startup, do best effort conflict resolution and run `npm install the package@version` if the package is not in `package.json` already (Thanks to @thheller on #shadow-cljs on clojurians Slack for that explanation). 
Without this change, depending on reagent results in the following issue:
```
[:app] Build failure:
The required namespace "react" is not available, it was required by …
```

Support shadow-cljs

---

doc/CreatingReagentComponents.md

`what the reagent component` is a blog post that gets into the nitty gritty details of what it means when the docs say "underneath they are all just React components".  
If there is anything missing from a technical perspective, I am happy to correct 😄

Enhance Docs w/ link to reagent component blog

---

CHANGELOG.md
package.json
project.clj
src/deps.cljs
src/reagent/core.cljs
src/reagent/impl/batching.cljs
src/reagent/impl/component.cljs
src/reagent/impl/template.cljs
src/reagent/impl/util.cljs
test/reagent/impl/util_test.cljs
test/reagenttest/testreagent.cljs

- Adds support for using `UNSAFE_` lifecycle methods.
- Migrates Reagent implementation away from `componentWillMount` to `componentDidMount` to avoid deprecation warnings.
- Separated `getInitialState` and `constructor` methods, they work differently
- Tested & improved support for `getDerivedState` methods and `getSnapshotBeforeUpdate`
I'm also interested in trying out if we could generate functional components in some cases, but I guess that will be a separate, bigger, PR.
TODO: I'll test this in few work projects to ensure everything is still working.

React 16.9

---

doc/CreatingReagentComponents.md

Without the empty params vector, the columns example caused compilation errors when including it in a script.

Fix error in CreatingReagentComponents.md

---

.gitignore
package-lock.json
package.json
project.clj
shadow-cljs.edn
src/reagent/impl/batching.cljs
src/reagent/impl/component.cljs
src/reagent/impl/template.cljs
src/reagent/impl/util.cljs
src/reagent/ratom.cljs
test-environments/shadow-cljs-prod/karma.conf.js
test-environments/shadow-cljs-prod/test.sh
test/reagenttest/testreagent.cljs

TODO: Run shadow-cljs or figwheel-main tests with advanced compilation because this is probably currently missing some hints.

Fix #460: Add type hints for extern inference

---

CHANGELOG.md
doc/ReactFeatures.md
src/reagent/impl/component.cljs

We already support the static contextTypes and childContextTypes from the legacy
context API. React has now added contextType to the new Context API to make it
easier to consume the context value.
https://reactjs.org/docs/context.html#classcontexttype
https://reactjs.org/blog/2018/10/23/react-v-16-6.html

Add support for Class.contextType

---

src/reagent/impl/batching.cljs
src/reagent/impl/component.cljs
test/reagenttest/testreagent.cljs

Parent components need to have smaller mount-order numbers than their
children, or else this will break when only the children are rerendered
and get new number.
Fixes #462

Use component constructor to keep track of mount order

---

src/reagent/ratom.cljs

Hopefully a fairly uncontroversial PR! 
Including path can help track down which particular cursor is misbehaving, ie in a React Native project, I have the following error message:
This isn't particularly helpful, but when the path is included it becomes a lot easier to find which particular cursor is responsible for the assert failure.

Include path in assert error for cursors

---

doc/UsingHiccupToDescribeHTML.md

Looks like it's just out of date now render is being moved into a separate namespace? Hope this helps! Thanks 😄

Update reference to reagent.dom from reagent.core

---

README.md

we replace the function, 
reagent.core/render -> reagent.dom/render

Update README since function namespace was changed

---

src/reagent/impl/util.cljs
test/reagent/impl/util_test.cljs

This PR fixes a minor issue with `merge-props`. When called with 2 or more arguments without a `:class` key `merge-props` returns a result with `:class nil`. `semantic-ui-react` interprets the presence of `:class` key with value `nil`  as "remove all classes from the component".
This fix does not add `:class` key at all if no classes are present in the arguments to `merge-props`.
[Test run log](https://gist.github.com/achikin/e01c6106ec824d9d2faa9024d67cd154)

Fix merge-props without classes

---

CHANGELOG.md
codecov.yml
doc/ReactFeatures.md
doc/ReagentCompiler.md
examples/functional-components-and-hooks/README.md
examples/functional-components-and-hooks/project.clj
examples/functional-components-and-hooks/resources/public/example.css
examples/functional-components-and-hooks/resources/public/index.html
examples/functional-components-and-hooks/src/example/core.cljs
project.clj
src/reagent/core.cljs
src/reagent/dom.cljs
src/reagent/dom/server.cljs
src/reagent/impl/component.cljs
src/reagent/impl/input.cljs
src/reagent/impl/protocols.cljs
src/reagent/impl/template.cljs
src/reagent/impl/util.cljs
src/reagent/ratom.cljs
test/reagent/impl/template_test.cljs
test/reagent/impl/util_test.cljs
test/reagenttest/performancetest.cljs
test/reagenttest/runtests.cljs
test/reagenttest/testreagent.cljs
test/reagenttest/testwrap.cljs
test/reagenttest/utils.cljs

Current status: nearly all test cases are working with the new implementation, done some testing with real work projects and seems to be working.
Next steps:
- Create snapshot release for testing
- Find a way to compare performance to Class components

Test creating functional components

---

examples/react-mde/Readme.md
examples/react-mde/package-lock.json
examples/react-mde/package.json
examples/react-mde/resources/public/index.html
examples/react-mde/resources/public/react-mds-all.css
examples/react-mde/shadow-cljs.edn
examples/react-mde/src/example/core.cljs

Hi,
I spent almost an entire day last week trying to get reagent working with a library called react-mde, which renders a simple Markdown editor. The main issue was the `textarea` component, similar to what happens with `material-ui`. I finally got it working after some help from the clojurians slack channel. The trick was to use React's `forwardRef`.
Since I didn't see any example of using the cursor positioning fix with `forwardRef`, I thought I could make a small example and see if you would be willing to add it. Maybe it will save someone some time in the future.
This PR adds an example with three cases:
1. The editor without any fix (cursor positioning misbehaves)
2. The editor with the custom textarea component, but without the use of forwardRef (cursor behaves well, but …

Adds example for using react-mde with custom textarea and forwardRef

---

doc/ReactFeatures.md

Re-balance parens.
Read the error state instead of a missing atom.

Fix error-boundary example

---

CHANGELOG.md
src/reagent/core.clj
src/reagent/core.cljs

Fixes #501 
Not if it is a good idea to throw error tagged as `:cljs/analysis-error` but this would show quite clear error to the user and block the compilation.
In Figwheel:
```
Failed to compile build :client from ["demo"] in 0.592 seconds.
----  Could not Analyze  demo/reagentdemo/intro.cljs   line:66  column:3  ----
reagent.core/render function was moved to reagent.dom namespace in Reagent v1.0
65  (defn render-simple []
66    (r/render
^--- reagent.core/render function was moved to reagent.dom namespace in Reagent v1.0
67      [simple-component]
68      (.-body js/document)))
----  Analysis Error : Please see demo/reagentdemo/intro.cljs  ----
```
In Shadow-cljs:
```
[:app] Build failure:
------ ERROR -------------------------------------------------------------------
File: …
```

Add reagent.core/render placeholder, throwing informative runtime error

---

README.md

Looks like this got missed when the function moved between namespaces.

Update README to use correct namespace alias for call to dom-node

---

demo/reagentdemo/intro.cljs

It looks like `reagent.dom` is not being included in the `ns` form under the "Essential API" section of the [intro page](http://reagent-project.github.io/).
I think this PR fixes the issue, but I'm not sure what other changes may need to be made in order to push out the fix to the page itself.

add reagent.dom to ns form for "Essential API" example

---

src/reagent/impl/template.cljs

We had some tests in our application break after we updated reagent from 0.9. to 1.x which were completely separated from actual view code or anything related to reagent. The reason was the generated symbols with gensym in our code had shifted up by one. Taking a look in reagent code, I saw that all gensym calls except the one in create-compiler used a custom prefix. I think it would be a good idea to add one there too so that reagent code doesn't affect the output of gensym in the application code.

Add prefix to gensym call in create-compiler

---

CHANGELOG.md
src/reagent/impl/component.cljs
test/reagenttest/testreagent.cljs

React componentStack information at least will use these names.

Fix #549: Add name property to classes and fns created by Reagent

---

doc/ManagingState.md

I was convinced that this example was broken until I ran the code myself and... it worked as described! The bad indentation obscures the data.

Fix indentation.

---

src/reagent/ratom.clj

This will properly silence the warning generated by recent shadow-cljs versions.
The warning is new since older versions only accounted for values tagged as `any`. But in cases like the `with-let-values` it is tagged as `#{any array}` due to the `if` branch having a hardcoded array return value. So, no externs inference was ever warned about.
In this case it is not a problem and technically no externs are needed. However in other projects under different circumstances the missing warnings could lead to build failures due to missing externs. So this change was added and uncovered a lot of previously missed cases, this being one of them.

tag with-let macro symbol to silence infer warning

---

src/clj-kondo/clj-kondo.exports/reagent/reagent/config.edn

Address part of what is described in
- https://github.com/reagent-project/reagent/issues/610
I think that this small contribution
- makes it easier for "newbies" to use reagent in a kondo-powered IDE (clojure-lsp is powered by kondo)
- facilitates and avoids explicit kondo configuration for simple use-cases
I plan to do a full implementation (via hooks, supporting finally) soon.

Add a basic clj-kondo config for library consumers

---

.gitignore
doc/ReactFeatures.md

A simple code example of server-side rendering with `reagent.dom.server/render-to-string`
Related #302

Add documentation/example for SSR

---

src/reagent/core.cljs
src/reagent/impl/template.cljs
test/reagenttest/testreagent.cljs

See https://github.com/reagent-project/reagent/blob/master/doc/Security.md
This does prevent ONE case where EDN/Transit could be used to create arbitrary HTML elements without going through React.
The `convert-props` is on a very often called code-path, but I hope one JS property check is not too bad. The Clojure map to JS object conversion is already quite slow.

Only allow UnsafeHtml values for :dangerouslySetInnerHTML

---

examples/geometry/shadow-cljs.edn

Updated the Shadow CLJS :init-fn to refer to the `run` function.
Before this change, `npm shadow-cljs watch :app` failed with:
```
[:app] Build failure:
Invalid configuration
-- Spec failed --------------------
{:target ...,
:output-dir ...,
:asset-path ...,
:devtools ...,
:modules {:main {:entries ..., :init-fn geometry.core}},
^^^^^^^^^^^^^
:build-id ...}
should satisfy
unquoted-qualified-symbol?
```

Fix geometry example build

---

src/reagent/dom/client.cljs
src/reagent/impl/batching.cljs

This will avoid double queuing when Reagent has already queued components to render due to ratom changes.

Try using flushSync when flushing Reagent render queue

---

.clj-kondo/config.edn
CHANGELOG.md
demo/reagentdemo/intro.cljs
src/clj-kondo/clj-kondo.exports/reagent/reagent/config.edn
src/reagent/core.clj
src/reagent/impl/component.cljs
src/reagent/impl/template.cljs
src/reagent/impl/util.clj
test/reagenttest/testreagent.cljs

From #598 but without the fast refresh support
Allow creating functional components that can be used with the magic `:f>` "shortcut".

Add defc macro to create fn components
