- .gitignore
- CHANGELOG.md
- README.md
- src/reagent/impl/template.cljs
I've done what I can, you can see I added another issue about how to run tests & etc.
I've tested this in a branch of my project and it works fine as far as I can tell.  It's not something that you use everywhere, but it can be nice (especially with things like Bootstrap, which can deeply nest elements).
If this gets accepted, I have ideas about making it easier to include XML/HTML entities. I sure would like an easy way to &nbsp; , etc.
> 142 extended hiccup

- project.clj
I tried upgrading React to the latest version. It should only contain internal changes.
All examples on the project page worked fine.
I ran tests on my machine with latest Chrome, Safari and Firefox, no errors:
Ran 93 tests containing 2034 assertions.
0 failures, 0 errors.
> Upgrade to latest React

- package.json
- project.clj
The latest release of react is primarily a bug fix one. See [notes](https://github.com/facebook/react/releases/tag/v15.0.2) for details.
> Updated react to latest version. [15.0.1 -> 15.0.2]

- project.clj
I've run the tests and they all pass.
Changelog of React is [here](https://github.com/facebook/react/releases/tag/v15.1.0). Its mostly a bug fix release.
> Upgraded React to v15.1.0

- src/reagent/core.cljs
Just fixing up some indentation.
> Fix doc formatting

- package.json
- project.clj
See the changelog [here](https://github.com/facebook/react/releases/tag/v15.2.1)
> Upgraded React to v15.2.1

- circle.yml
This uses the existing test commands running against node. It could be enhanced in the future, but this would be a good start.
Fixes #168
> Add circle.yml file to run tests

- demo/reagentdemo/intro.cljs
- demo/sitetools/core.cljs
- project.clj
- src/reagent/core.cljs
- test/reagenttest/testreagent.cljs
> Update to React 15.4.0 and drop dom-server functions from core

- demo/reagentdemo/core.cljs
> Add link to API documentation

- examples/geometry/src/geometry/geometry.cljs
- project.clj
- src/reagent/impl/batching.cljs
- src/reagent/impl/template.cljs
- src/reagent/ratom.cljs
> Deftype constrcutors

- project.clj
- src/reagent/impl/component.cljs
- src/reagent/impl/util.cljs
- test/reagenttest/testreagent.cljs
> Update to React 15.5, use create-react-class

- src/reagent/impl/template.cljs
- test/reagenttest/testreagent.cljs
> Implement :<> hiccup tag for fragments

- CHANGELOG.md
- project.clj
- src/reagent/impl/template.cljs
- test/reagent/impl/template_test.cljs
- test/reagenttest/runtests.cljs
- test/reagenttest/testreagent.cljs
> Class fixes

- demo/reagentdemo/intro.cljs
We should always _care_ about performance; hopefully we don’t have to _think_ about it too often ;)
> Tweak to copy in demo/intro

- doc/UsingSquareBracketsInsteadOfParens.md
The links to `CreatingReagentComponents.md` were broken.
> Fix documentation links

- demo/reagentdemo/intro.cljs
The example has glitch due to stale atom state that triggers when the user first drags the BMI control and then the height control.
This PR proposes a fix in which the state dereferencing and calculation is separated from each other and the latter is performed eagerly in the update handler.
> Fix the BMI example in the introduction

- doc/ReactFeatures.md
> improve docs about using portal

- circle.yml
- demo/reagentdemo/dev.cljs
- demo/sitetools/core.cljs
- deps.edn
- package-lock.json
- package.json
- run-tests.sh
- test-environments/bundle-adv/README.md
- test-environments/bundle-adv/build.edn
- test-environments/bundle-adv/build.sh
- test-environments/bundle-adv/karma.conf.js
- test-environments/bundle-adv/karma.edn
- test-environments/bundle-adv/test.sh
- test-environments/bundle-adv/webpack.config.js
- test-environments/bundle/build.edn
- test-environments/bundle/karma.conf.js
- test-environments/bundle/test.sh
- test-environments/bundle/webpack.config.js
- test-environments/bundle/workaround.js
- test/reagenttest/runtests.cljs
- test/reagenttest/testreagent.cljs
Testing out new cljs bundle output. Will add advanced version also.
> Bundle test

- doc/development.md
A tiny fix of prepare-tests.sh name.
> Fix dev doc

- doc/README.md
`Controlled Inpits` -> `Controlled Inputs`
> Fix typo in docs

- doc/InteropWithReact.md
This pull request just fixes some missing closing brackets in the docs.
> Add missing brackets

- doc/CreatingReagentComponents.md
Fixes the broken link to the blog post _What the Reagent Component?!_.
> Fix broken link in doc/CreatingReagentComponents.md

- doc/UsingHiccupToDescribeHTML.md
> Document passing CSS custom properties

- doc/UsingHiccupToDescribeHTML.md
> Document creating non standard HTML attributes

- src/reagent/ratom.cljs
- test/reagenttest/testratom.cljs
e.g. to support posh!
```clojure
(defonce app-db (r/atom (or (unsave-app-db) {})))
(defonce conn (with-meta (r/cursor app-db [:ds-db]) {:listeners (atom {})}))
(pr/posh! conn)
```
> Add meta to RCursor.
